apiVersion: v2
name: voting-app
description: Umbrella chart a voting-app on EKS
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: redis
    version: "23.2.2"
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: postgresql
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: ">=18.0.0 <19.0.0"
